spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: your_db_user
    password: your_db_password
    driver-class-name: oracle.jdbc.OracleDriver

  batch:
    job:
      enabled: false  # We'll launch via scheduler manually
    jdbc:
      initialize-schema: always  # we manage schema manually

logging:
  level:
    root: INFO
    com.example.batch: DEBUG
  file:
    name: logs/batch-job.log

app:
  rest:
    endpoint: http://localhost:8080/api/orders

retry:
  max-attempts: 3
  backoff-delay: 2000

server:
  port: 8081
