# application-dev.yml - Development environment configuration

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1  # Oracle DB URL for dev
    username: batch_user                           # DB username
    password: batch_password                       # DB password
    driver-class-name: oracle.jdbc.OracleDriver    # Oracle JDBC driver

  sql:
    init:
      mode: always                                  # Always run SQL init scripts on startup
      schema-locations: classpath:schema-batch-oracle.sql  # Path to Spring Batch schema script
      continue-on-error: true                       # Skip errors if schema already exists

  batch:
    job:
      enabled: false                                # Don't auto-start jobs; launch manually or via scheduler
    jdbc:
      initialize-schema: never                      # Let us control schema creation using sql.init

logging:
  level:
    root: INFO                                      # General logging level
    com.example.batch: DEBUG                        # Project-specific debug level
  file:
    name: logs/app-dev.log                          # Output log file for development

scheduler:
  cron: "0 0/5 * * * ?"                             # Cron expression: run job every 5 minutes

retry:
  max-attempts: 3                                   # Retry failed REST calls up to 3 times
  delay: 2000                                       # 2-second delay between retries

rest:
  endpoint:
    url: https://dev-api.example.com/orders         # Target REST endpoint for JSON submission
