spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: oracle_user
    password: oracle_password
    driver-class-name: oracle.jdbc.OracleDriver

  batch:
    job:
      enabled: true
    initialize-schema: always

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.example.batch: DEBUG
