spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: batch_user
    password: batch_password
    driver-class-name: oracle.jdbc.OracleDriver

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never  # we manage schema manually

logging:
  level:
    root: INFO
    com.example.batch: DEBUG
  file:
    name: logs/batch-job.log

api:
  endpoint:
    url: http://localhost:8081/api/orders

retry:
  max-attempts: 3
  backoff-delay: 2000
