# application-test.yml - Testing configuration (in-memory database)

spring:
  datasource:
    url: jdbc:h2:mem:testdb                          # In-memory H2 database
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-batch-h2.sql
      continue-on-error: true

  batch:
    job:
      enabled: true                                  # Auto-start job for test runs
    jdbc:
      initialize-schema: always

logging:
  level:
    root: DEBUG
    com.example.batch: DEBUG

scheduler:
  cron: "0 0/1 * * * ?"                              # Cron: every minute (for quick testing)

retry:
  max-attempts: 2
  delay: 1000

rest:
  endpoint:
    url: http://localhost:8081/mock-orders
